# Generated by Django 2.2.14 on 2021-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_convertdata_uploadcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='document',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
