# Generated by Django 2.2.14 on 2021-09-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210902_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertData',
        ),
        migrations.AddField(
            model_name='uploadcsv',
            name='csv_file_name',
            field=models.CharField(default='pankaj', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcsv',
            name='sql_file_name',
            field=models.CharField(default='file', max_length=256),
            preserve_default=False,
        ),
    ]
